import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MobileNavbar from '@/components/MobileNavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <div className="hidden xl:block">
        <Navbar />
      </div>
      <div className="block xl:hidden">
        <MobileNavbar />
      </div>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
