import Navbar from '@/components/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MobileNavbar from '@/components/MobileNavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#f0edf1] text-dark-purple text-xl`}
      >
        <div className="hidden xl:block">
          <Navbar />
        </div>
        <div className="block xl:hidden">
          <MobileNavbar />
        </div>
        {children}
      </body>
    </html>
  )
}
